### ISSUE TITLE
Lacking interface to detect end of zlib stream

### ISSUE THREAD

**Issue by bgamari** [fpco/streaming-commons#28]
Some unfortunate data sources consist of several gzip streams concatenated together. When inflating such a source the zlib inflater will eventually enter `Z_STREAM_END`, at which point one needs to continue inflation with a new inflater. Unfortunately there is currently no way to detect this condition. See https://github.com/snoyberg/zlib-bindings/issues/10 for motivation.

**Comment by snoyberg** [comment]
This looks like the same request as https://github.com/snoyberg/conduit/issues/254, which turned out to require no changes to streaming-commons, and was able to be implemented with the preexisting interface (though a helpful combinator from conduit-extra helped out). In your case, I wrote the following program which seems to have the behavior you're looking for:

```haskell
#!/usr/bin/env stack
-- stack runghc --resolver lts-5.8 --package conduit-extra
import Data.Conduit.Zlib (ungzip, multiple)
import Data.Conduit.Binary (sourceHandle, sinkHandle)
import Data.Conduit (($$), (=$))
import System.IO (stdin, stdout)

main :: IO ()
main =
    sourceHandle stdin
    $$ multiple ungzip
    =$ sinkHandle stdout
```

Can you test that out?

**Comment by bgamari** [comment]
Michael Snoyman <notifications@github.com> writes:

> Can you test that out?

Ahh, I should have read the haddocks more carefully; Indeed that seems
to do the trick. Thanks!

**Comment by snoyberg** [comment]
Glad it works
